// Seed data for the Products module (Lecture 2). Spread across 4 categories
// with a handful marked isFeatured so the frontend's "Featured" home section
// has something to render. Images are placeholder URLs from picsum.photos.
const products = [
  {
    name: "Wireless Bluetooth Headphones",
    description:
      "Over-ear wireless headphones with active noise cancellation, 30-hour battery life, and a foldable design for easy travel.",
    price: 79.99,
    image: "https://picsum.photos/seed/headphones/600/600",
    images: [
      "https://picsum.photos/seed/headphones-2/600/600",
      "https://picsum.photos/seed/headphones-3/600/600",
    ],
    category: "Electronics",
    brand: "SoundCore",
    countInStock: 45,
    rating: 4.5,
    numReviews: 128,
    isFeatured: true,
  },
  {
    name: "Smart Fitness Watch",
    description:
      "Track heart rate, sleep, and workouts with this water-resistant smart watch. Includes a 7-day battery and phone notifications.",
    price: 129.99,
    image: "https://picsum.photos/seed/smartwatch/600/600",
    images: ["https://picsum.photos/seed/smartwatch-2/600/600"],
    category: "Electronics",
    brand: "FitTrack",
    countInStock: 30,
    rating: 4.3,
    numReviews: 96,
    isFeatured: false,
  },
  {
    name: "Portable Bluetooth Speaker",
    description:
      "Compact, splash-proof Bluetooth speaker with 12 hours of playtime and surprisingly deep bass for its size.",
    price: 49.99,
    image: "https://picsum.photos/seed/speaker/600/600",
    images: [],
    category: "Electronics",
    brand: "SoundCore",
    countInStock: 60,
    rating: 4.1,
    numReviews: 54,
    isFeatured: false,
  },
  {
    name: "4K Ultra HD Action Camera",
    description:
      "Waterproof action camera that shoots 4K video at 60fps, with a wide-angle lens and a full mounting accessory kit included.",
    price: 199.99,
    image: "https://picsum.photos/seed/actioncam/600/600",
    images: ["https://picsum.photos/seed/actioncam-2/600/600"],
    category: "Electronics",
    brand: "GoView",
    countInStock: 18,
    rating: 4.6,
    numReviews: 41,
    isFeatured: false,
  },
  {
    name: "Men's Classic Denim Jacket",
    description:
      "A timeless denim jacket with a comfortable regular fit, button closure, and two chest pockets. Pairs with everything.",
    price: 59.99,
    image: "https://picsum.photos/seed/denimjacket/600/600",
    images: [],
    category: "Clothing",
    brand: "Urban Thread",
    countInStock: 40,
    rating: 4.2,
    numReviews: 33,
    isFeatured: true,
  },
  {
    name: "Women's Running Shoes",
    description:
      "Lightweight running shoes with breathable mesh uppers and cushioned soles built for daily training runs.",
    price: 89.99,
    image: "https://picsum.photos/seed/runningshoes/600/600",
    images: ["https://picsum.photos/seed/runningshoes-2/600/600"],
    category: "Clothing",
    brand: "StrideFit",
    countInStock: 55,
    rating: 4.7,
    numReviews: 210,
    isFeatured: false,
  },
  {
    name: "Cotton Crew Neck T-Shirt (3-Pack)",
    description:
      "Soft, breathable 100% cotton t-shirts in a pack of three. Machine washable and available in classic colors.",
    price: 24.99,
    image: "https://picsum.photos/seed/tshirt/600/600",
    images: [],
    category: "Clothing",
    brand: "Urban Thread",
    countInStock: 100,
    rating: 4.0,
    numReviews: 72,
    isFeatured: false,
  },
  {
    name: "Slim Fit Chino Pants",
    description:
      "Versatile slim fit chinos made from stretch cotton twill, comfortable enough for the office or the weekend.",
    price: 44.99,
    image: "https://picsum.photos/seed/chinos/600/600",
    images: [],
    category: "Clothing",
    brand: "Urban Thread",
    countInStock: 35,
    rating: 4.1,
    numReviews: 19,
    isFeatured: false,
  },
  {
    name: "Stainless Steel Cookware Set",
    description:
      "10-piece stainless steel cookware set with tempered glass lids, oven-safe up to 500°F and dishwasher safe.",
    price: 149.99,
    image: "https://picsum.photos/seed/cookware/600/600",
    images: ["https://picsum.photos/seed/cookware-2/600/600"],
    category: "Home & Kitchen",
    brand: "ChefPro",
    countInStock: 15,
    rating: 4.8,
    numReviews: 87,
    isFeatured: true,
  },
  {
    name: "Automatic Drip Coffee Maker",
    description:
      "12-cup programmable coffee maker with a reusable filter, auto shut-off, and a keep-warm plate.",
    price: 39.99,
    image: "https://picsum.photos/seed/coffeemaker/600/600",
    images: [],
    category: "Home & Kitchen",
    brand: "BrewWell",
    countInStock: 28,
    rating: 4.3,
    numReviews: 64,
    isFeatured: false,
  },
  {
    name: "Memory Foam Pillow (2-Pack)",
    description:
      "Contoured memory foam pillows with a breathable cover, designed to support proper neck alignment while you sleep.",
    price: 34.99,
    image: "https://picsum.photos/seed/pillow/600/600",
    images: [],
    category: "Home & Kitchen",
    brand: "RestEase",
    countInStock: 50,
    rating: 4.4,
    numReviews: 102,
    isFeatured: false,
  },
  {
    name: "Non-Stick Frying Pan Set",
    description:
      "3-piece non-stick frying pan set in three common sizes, with heat-resistant handles and even heat distribution.",
    price: 29.99,
    image: "https://picsum.photos/seed/fryingpan/600/600",
    images: [],
    category: "Home & Kitchen",
    brand: "ChefPro",
    countInStock: 32,
    rating: 4.0,
    numReviews: 27,
    isFeatured: false,
  },
  {
    name: "Yoga Mat with Carrying Strap",
    description:
      "Extra-thick 6mm yoga mat with a non-slip surface on both sides, includes a carrying strap for the gym or studio.",
    price: 19.99,
    image: "https://picsum.photos/seed/yogamat/600/600",
    images: [],
    category: "Sports & Outdoors",
    brand: "FlexFit",
    countInStock: 70,
    rating: 4.5,
    numReviews: 58,
    isFeatured: false,
  },
  {
    name: "Adjustable Dumbbell Set",
    description:
      "Space-saving adjustable dumbbell set, 5-50 lbs per dumbbell, with a quick-select dial to change weight in seconds.",
    price: 249.99,
    image: "https://picsum.photos/seed/dumbbells/600/600",
    images: ["https://picsum.photos/seed/dumbbells-2/600/600"],
    category: "Sports & Outdoors",
    brand: "FlexFit",
    countInStock: 12,
    rating: 4.9,
    numReviews: 39,
    isFeatured: true,
  },
];

module.exports = products;
